version: '2'
services:

  mongodb:
    image: mongo:4
    container_name: 'mongodb'
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      # use a script to configure graylog authentication 
      #- ./scripts/graylog_mongo.js:/docker-entrypoint-initdb.d/graylog.js:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: 'elasticsearch'
    restart: unless-stopped
    environment:
      # configured for single node, non production
      - http.host=0.0.0.0
      - path.repo=/mnt/shared/elasticsearch
      - transport.host=localhost
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2000000000
    ports:
      - 9200:9200
    volumes:
      - ./usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - /mnt/shared/elasticsearch:/mnt/shared/elasticsearch

  graylog:
    image: graylog/graylog:3.0
    container_name: 'graylog'
    hostname: 'logs.mobile.verity.org'
    restart: unless-stopped
    volumes:
      - ./usr/share/graylog/data/journal:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=UqIEfTujSpQAaHba93WFdf3ySHcIA2L5WirX7G8ez6tpHJFoE33uUJ0GVkFYnnpeYArButIkwSfodSL8aEYCWOqHRstj3ZYl
      - GRAYLOG_ROOT_TIMEZONE=America/Los_Angeles
      - GRAYLOG_ROOT_PASSWORD_SHA2=fe2b60d1d85bc258e96cb8630431df2fff941a405044b9a99194595316ed1087
      - GRAYLOG_ROOT_EMAIL=theodorespecht@verity.org
      - GRAYLOG_HTTP_EXTERNAL_URI=https://logs.mobile.verity.org/
      - GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
      - GRAYLOG_TRANSPORT_EMAIL_PROTOCOL=smtp
      - GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=SMTP.AD.VERITY.ORG
      - GRAYLOG_TRANSPORT_EMAIL_PORT=25
      - GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=false
      - GRAYLOG_TRANSPORT_EMAIL_USE_TLS=false
      - GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false
      - GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=https://logs.mobile.verity.org/api
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Raw/Plaintext TCP
      - 5555:5555 
      # beats collector
      - 5044:5044 
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      #- 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      #- 12201:12201/udp

  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.6.1"
    container_name: 'kibana'
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped
    environment:
      #SERVER_NAME: kibana.example.org
      #SERVER_HOST: "0"
      #KIBANA_DEFAULTAPPID kibana.defaultAppId
      #XPACK_MONITORING_ENABLED: xpack.monitoring.enabled 
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
